spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/campus
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: DaviiD98
  jpa:
    hibernate:
      enable_lazy_load_no_trans: true
      ddl-auto: update
  
               
    
    
            

azure:
  storage:
    
    account-name: storagetesisug
    default-endpoints-protocol: https
    endpoint-suffix: core.windows.net

        
server:
  port: 8090