spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/campus
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: DaviiD98
  jpa:
    hibernate:
      ddl-auto: update

      
server:
  port: 8090